# Generated by Django 4.2.2 on 2023-07-29 00:40

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_order_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.IntegerField(default=app.models.random_id, primary_key=True, serialize=False, unique=True)),
                ('card_number', models.CharField(default=' ', max_length=80)),
                ('expiration_date', models.CharField(blank=True, default=' ', max_length=5)),
                ('security_code', models.CharField(blank=True, default=' ', max_length=80)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(default=app.models.random_id, primary_key=True, serialize=False, unique=True)),
                ('street_address', models.CharField(blank=True, default=' ', max_length=50)),
                ('apartment_suite', models.CharField(blank=True, default=' ', max_length=50)),
                ('city', models.CharField(blank=True, default=' ', max_length=30)),
                ('state', models.CharField(blank=True, default=' ', max_length=30)),
                ('zip_code', models.CharField(blank=True, default=' ', max_length=30)),
                ('contact_phone', models.CharField(blank=True, default=' ', max_length=30)),
                ('contact_email', models.CharField(blank=True, default=' ', max_length=30)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
