# Generated by Django 4.2.2 on 2023-07-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_paymentdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='account_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='account_id',
            field=models.IntegerField(),
        ),
    ]
