# Generated by Django 4.0 on 2023-07-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_address_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment_suite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
    ]
