# Generated by Django 4.0 on 2023-07-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_user_apartment_suite_remove_user_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='newReleases',
            field=models.BooleanField(default=False),
        ),
    ]
